#! /bin/sh

sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           3
bspc config top_padding          0
bspc config bottom_padding       0
bspc config right_padding        0
bspc config left_padding         0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a scratchpad sticky=on state=floating hidden=on
#bspc rule -a qq state=floating

bspc rule -a Telegram state=floating
bspc rule -a TelegramDesktop state=floating
bspc rule -a mitalk state=floating
bspc rule -a jetbrains-studio state=floating
bspc rule -a Surf state=tiled
